name: kannapy
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  modal_progress_hud: ^0.1.3
  intl:
  mailer:
  animations: null
  animator: null
  auto_size_text: null
  bot_toast: null
  cached_network_image: null
  carousel_slider: null
  cloud_functions: null
  country_list_pick: null
  cupertino_icons: ^0.1.2
  cloud_firestore: null
  firebase_auth: null
  firebase_database: null
  firebase_messaging: null
  firebase_storage: null
  flutter_app_badger: null
  flutter_datetime_picker: ^1.4.0
  flutter_inner_drawer: null
  flutter_local_notifications: null
  flutter_markdown: ^0.4.4
  flutter_neumorphic: ^3.0.2
  flutter_widgets: null
  font_awesome_flutter: null
  google_sign_in: null
  http: null
  image: null
  image_picker: null
  loading_animations: null
  page_transition: null
  path_provider: null
  photo_view: null
  pull_to_refresh: null
  share: null
  shared_preferences: null
  slide_countdown_clock: null
  sliding_up_panel: null
  stripe_payment: null
  timeago: null
  timer_count_down: null
  url_launcher: null
  uuid: null
  youtube_player_flutter: ^7.0.0+7
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/kannapy_logo.jpg
    - assets/images/kannapy_logo_splash.jpg
    - assets/images/kannapyLogo.png
    - assets/terms_n_cond.md
    - assets/privacy_policy.md
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
